### ISSUE TITLE
Invalid character in header content ["WWW-Authenticate"]

### ISSUE THREAD

**Issue by cantoraz** [Jeff-Tian/passport-weapp#8]
https://github.com/Jeff-Tian/passport-weapp/blob/ea65c038b9d67eb6fc42522854f43cce88741fec/lib/strategy.js#L122

It's not recommended to use non-us-ascii characters in HTTP header value.

The `passport` package will use the `challenge` parameter as value of `WWW-Authenticate` header. Most HTTP frameworks can't handle this correctly, eg, `Egg.js` based on `koa.js`. In consequence, the server generate a `500` internal error, rather than the expected `401`.

[https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L169](https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L169)
```
if (res.statusCode == 401 && rchallenge.length) {
  res.setHeader('WWW-Authenticate', rchallenge);
}
```

**Comment by Jeff-Tian** [comment]
Thanks! Can you send a PR?

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
